/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as CandidatureRouteImport } from './routes/candidature'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedRecruitmentRouteImport } from './routes/_authenticated/recruitment'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPollsRouteImport } from './routes/_authenticated/polls'
import { Route as AuthenticatedPointsRouteImport } from './routes/_authenticated/points'
import { Route as AuthenticatedPdcRouteImport } from './routes/_authenticated/pdc'
import { Route as AuthenticatedObjectivesRouteImport } from './routes/_authenticated/objectives'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedEffectifRouteImport } from './routes/_authenticated/effectif'
import { Route as AuthenticatedDonationsRouteImport } from './routes/_authenticated/donations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedBlacklistRouteImport } from './routes/_authenticated/blacklist'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAbsencesRouteImport } from './routes/_authenticated/absences'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedPollsIndexRouteImport } from './routes/_authenticated/polls.index'
import { Route as ApiTestSeedPollRouteImport } from './routes/api/test/seed-poll'
import { Route as ApiTestLoginRouteImport } from './routes/api/test/login'
import { Route as ApiAuthWhoamiRouteImport } from './routes/api/auth/whoami'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedToolsXpCalculatorRouteImport } from './routes/_authenticated/tools.xp-calculator'
import { Route as AuthenticatedToolsStatusRouteImport } from './routes/_authenticated/tools.status'
import { Route as AuthenticatedToolsPlayerRouteImport } from './routes/_authenticated/tools.player'
import { Route as AuthenticatedToolsMarketRouteImport } from './routes/_authenticated/tools.market'
import { Route as AuthenticatedToolsLeaderboardRouteImport } from './routes/_authenticated/tools.leaderboard'
import { Route as AuthenticatedToolsFactionRouteImport } from './routes/_authenticated/tools.faction'
import { Route as AuthenticatedToolsClickerRouteImport } from './routes/_authenticated/tools.clicker'
import { Route as AuthenticatedPollsIdRouteImport } from './routes/_authenticated/polls.$id'
import { Route as AuthenticatedMembersIdRouteImport } from './routes/_authenticated/members.$id'
import { Route as ApiPublicHooksSyncDiscordPresenceRouteImport } from './routes/api/public/hooks/sync-discord-presence'
import { Route as ApiPublicHooksPaladiumSyncRouteImport } from './routes/api/public/hooks/paladium-sync'
import { Route as ApiPublicBotVoiceRouteImport } from './routes/api/public/bot/voice'
import { Route as ApiPublicBotStatsRouteImport } from './routes/api/public/bot/stats'
import { Route as ApiPublicBotMessageRouteImport } from './routes/api/public/bot/message'
import { Route as ApiPublicBotMemberRouteImport } from './routes/api/public/bot/member'
import { Route as ApiPublicBotImportRouteImport } from './routes/api/public/bot/import'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatureRoute = CandidatureRouteImport.update({
  id: '/candidature',
  path: '/candidature',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecruitmentRoute =
  AuthenticatedRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPollsRoute = AuthenticatedPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPointsRoute = AuthenticatedPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdcRoute = AuthenticatedPdcRouteImport.update({
  id: '/pdc',
  path: '/pdc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedObjectivesRoute = AuthenticatedObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEffectifRoute = AuthenticatedEffectifRouteImport.update({
  id: '/effectif',
  path: '/effectif',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDonationsRoute = AuthenticatedDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlacklistRoute = AuthenticatedBlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAbsencesRoute = AuthenticatedAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedToolsRoute,
} as any)
const AuthenticatedPollsIndexRoute = AuthenticatedPollsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPollsRoute,
} as any)
const ApiTestSeedPollRoute = ApiTestSeedPollRouteImport.update({
  id: '/api/test/seed-poll',
  path: '/api/test/seed-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestLoginRoute = ApiTestLoginRouteImport.update({
  id: '/api/test/login',
  path: '/api/test/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWhoamiRoute = ApiAuthWhoamiRouteImport.update({
  id: '/api/auth/whoami',
  path: '/api/auth/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsXpCalculatorRoute =
  AuthenticatedToolsXpCalculatorRouteImport.update({
    id: '/xp-calculator',
    path: '/xp-calculator',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsStatusRoute =
  AuthenticatedToolsStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsPlayerRoute =
  AuthenticatedToolsPlayerRouteImport.update({
    id: '/player',
    path: '/player',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsMarketRoute =
  AuthenticatedToolsMarketRouteImport.update({
    id: '/market',
    path: '/market',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsLeaderboardRoute =
  AuthenticatedToolsLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsFactionRoute =
  AuthenticatedToolsFactionRouteImport.update({
    id: '/faction',
    path: '/faction',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsClickerRoute =
  AuthenticatedToolsClickerRouteImport.update({
    id: '/clicker',
    path: '/clicker',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedPollsIdRoute = AuthenticatedPollsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPollsRoute,
} as any)
const AuthenticatedMembersIdRoute = AuthenticatedMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMembersRoute,
} as any)
const ApiPublicHooksSyncDiscordPresenceRoute =
  ApiPublicHooksSyncDiscordPresenceRouteImport.update({
    id: '/api/public/hooks/sync-discord-presence',
    path: '/api/public/hooks/sync-discord-presence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaladiumSyncRoute =
  ApiPublicHooksPaladiumSyncRouteImport.update({
    id: '/api/public/hooks/paladium-sync',
    path: '/api/public/hooks/paladium-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotVoiceRoute = ApiPublicBotVoiceRouteImport.update({
  id: '/api/public/bot/voice',
  path: '/api/public/bot/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotStatsRoute = ApiPublicBotStatsRouteImport.update({
  id: '/api/public/bot/stats',
  path: '/api/public/bot/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotMessageRoute = ApiPublicBotMessageRouteImport.update({
  id: '/api/public/bot/message',
  path: '/api/public/bot/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotMemberRoute = ApiPublicBotMemberRouteImport.update({
  id: '/api/public/bot/member',
  path: '/api/public/bot/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotImportRoute = ApiPublicBotImportRouteImport.update({
  id: '/api/public/bot/import',
  path: '/api/public/bot/import',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidature': typeof CandidatureRoute
  '/forbidden': typeof ForbiddenRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/effectif': typeof AuthenticatedEffectifRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/me': typeof AuthenticatedMeRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/objectives': typeof AuthenticatedObjectivesRoute
  '/pdc': typeof AuthenticatedPdcRoute
  '/points': typeof AuthenticatedPointsRoute
  '/polls': typeof AuthenticatedPollsRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/polls/$id': typeof AuthenticatedPollsIdRoute
  '/tools/clicker': typeof AuthenticatedToolsClickerRoute
  '/tools/faction': typeof AuthenticatedToolsFactionRoute
  '/tools/leaderboard': typeof AuthenticatedToolsLeaderboardRoute
  '/tools/market': typeof AuthenticatedToolsMarketRoute
  '/tools/player': typeof AuthenticatedToolsPlayerRoute
  '/tools/status': typeof AuthenticatedToolsStatusRoute
  '/tools/xp-calculator': typeof AuthenticatedToolsXpCalculatorRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/whoami': typeof ApiAuthWhoamiRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/seed-poll': typeof ApiTestSeedPollRoute
  '/polls/': typeof AuthenticatedPollsIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/api/public/bot/import': typeof ApiPublicBotImportRoute
  '/api/public/bot/member': typeof ApiPublicBotMemberRoute
  '/api/public/bot/message': typeof ApiPublicBotMessageRoute
  '/api/public/bot/stats': typeof ApiPublicBotStatsRoute
  '/api/public/bot/voice': typeof ApiPublicBotVoiceRoute
  '/api/public/hooks/paladium-sync': typeof ApiPublicHooksPaladiumSyncRoute
  '/api/public/hooks/sync-discord-presence': typeof ApiPublicHooksSyncDiscordPresenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidature': typeof CandidatureRoute
  '/forbidden': typeof ForbiddenRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/donations': typeof AuthenticatedDonationsRoute
  '/effectif': typeof AuthenticatedEffectifRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/me': typeof AuthenticatedMeRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/objectives': typeof AuthenticatedObjectivesRoute
  '/pdc': typeof AuthenticatedPdcRoute
  '/points': typeof AuthenticatedPointsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/polls/$id': typeof AuthenticatedPollsIdRoute
  '/tools/clicker': typeof AuthenticatedToolsClickerRoute
  '/tools/faction': typeof AuthenticatedToolsFactionRoute
  '/tools/leaderboard': typeof AuthenticatedToolsLeaderboardRoute
  '/tools/market': typeof AuthenticatedToolsMarketRoute
  '/tools/player': typeof AuthenticatedToolsPlayerRoute
  '/tools/status': typeof AuthenticatedToolsStatusRoute
  '/tools/xp-calculator': typeof AuthenticatedToolsXpCalculatorRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/whoami': typeof ApiAuthWhoamiRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/seed-poll': typeof ApiTestSeedPollRoute
  '/polls': typeof AuthenticatedPollsIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/api/public/bot/import': typeof ApiPublicBotImportRoute
  '/api/public/bot/member': typeof ApiPublicBotMemberRoute
  '/api/public/bot/message': typeof ApiPublicBotMessageRoute
  '/api/public/bot/stats': typeof ApiPublicBotStatsRoute
  '/api/public/bot/voice': typeof ApiPublicBotVoiceRoute
  '/api/public/hooks/paladium-sync': typeof ApiPublicHooksPaladiumSyncRoute
  '/api/public/hooks/sync-discord-presence': typeof ApiPublicHooksSyncDiscordPresenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/candidature': typeof CandidatureRoute
  '/forbidden': typeof ForbiddenRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/_authenticated/absences': typeof AuthenticatedAbsencesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/blacklist': typeof AuthenticatedBlacklistRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/donations': typeof AuthenticatedDonationsRoute
  '/_authenticated/effectif': typeof AuthenticatedEffectifRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/objectives': typeof AuthenticatedObjectivesRoute
  '/_authenticated/pdc': typeof AuthenticatedPdcRoute
  '/_authenticated/points': typeof AuthenticatedPointsRoute
  '/_authenticated/polls': typeof AuthenticatedPollsRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recruitment': typeof AuthenticatedRecruitmentRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRouteWithChildren
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/members/$id': typeof AuthenticatedMembersIdRoute
  '/_authenticated/polls/$id': typeof AuthenticatedPollsIdRoute
  '/_authenticated/tools/clicker': typeof AuthenticatedToolsClickerRoute
  '/_authenticated/tools/faction': typeof AuthenticatedToolsFactionRoute
  '/_authenticated/tools/leaderboard': typeof AuthenticatedToolsLeaderboardRoute
  '/_authenticated/tools/market': typeof AuthenticatedToolsMarketRoute
  '/_authenticated/tools/player': typeof AuthenticatedToolsPlayerRoute
  '/_authenticated/tools/status': typeof AuthenticatedToolsStatusRoute
  '/_authenticated/tools/xp-calculator': typeof AuthenticatedToolsXpCalculatorRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/whoami': typeof ApiAuthWhoamiRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/seed-poll': typeof ApiTestSeedPollRoute
  '/_authenticated/polls/': typeof AuthenticatedPollsIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/api/public/bot/import': typeof ApiPublicBotImportRoute
  '/api/public/bot/member': typeof ApiPublicBotMemberRoute
  '/api/public/bot/message': typeof ApiPublicBotMessageRoute
  '/api/public/bot/stats': typeof ApiPublicBotStatsRoute
  '/api/public/bot/voice': typeof ApiPublicBotVoiceRoute
  '/api/public/hooks/paladium-sync': typeof ApiPublicHooksPaladiumSyncRoute
  '/api/public/hooks/sync-discord-presence': typeof ApiPublicHooksSyncDiscordPresenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidature'
    | '/forbidden'
    | '/legal'
    | '/login'
    | '/absences'
    | '/admin'
    | '/blacklist'
    | '/config'
    | '/dashboard'
    | '/donations'
    | '/effectif'
    | '/logs'
    | '/me'
    | '/members'
    | '/objectives'
    | '/pdc'
    | '/points'
    | '/polls'
    | '/profile'
    | '/recruitment'
    | '/staff'
    | '/tools'
    | '/welcome'
    | '/api/health'
    | '/members/$id'
    | '/polls/$id'
    | '/tools/clicker'
    | '/tools/faction'
    | '/tools/leaderboard'
    | '/tools/market'
    | '/tools/player'
    | '/tools/status'
    | '/tools/xp-calculator'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/whoami'
    | '/api/test/login'
    | '/api/test/seed-poll'
    | '/polls/'
    | '/tools/'
    | '/api/public/bot/import'
    | '/api/public/bot/member'
    | '/api/public/bot/message'
    | '/api/public/bot/stats'
    | '/api/public/bot/voice'
    | '/api/public/hooks/paladium-sync'
    | '/api/public/hooks/sync-discord-presence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidature'
    | '/forbidden'
    | '/legal'
    | '/login'
    | '/absences'
    | '/admin'
    | '/blacklist'
    | '/config'
    | '/dashboard'
    | '/donations'
    | '/effectif'
    | '/logs'
    | '/me'
    | '/members'
    | '/objectives'
    | '/pdc'
    | '/points'
    | '/profile'
    | '/recruitment'
    | '/staff'
    | '/welcome'
    | '/api/health'
    | '/members/$id'
    | '/polls/$id'
    | '/tools/clicker'
    | '/tools/faction'
    | '/tools/leaderboard'
    | '/tools/market'
    | '/tools/player'
    | '/tools/status'
    | '/tools/xp-calculator'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/whoami'
    | '/api/test/login'
    | '/api/test/seed-poll'
    | '/polls'
    | '/tools'
    | '/api/public/bot/import'
    | '/api/public/bot/member'
    | '/api/public/bot/message'
    | '/api/public/bot/stats'
    | '/api/public/bot/voice'
    | '/api/public/hooks/paladium-sync'
    | '/api/public/hooks/sync-discord-presence'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/candidature'
    | '/forbidden'
    | '/legal'
    | '/login'
    | '/_authenticated/absences'
    | '/_authenticated/admin'
    | '/_authenticated/blacklist'
    | '/_authenticated/config'
    | '/_authenticated/dashboard'
    | '/_authenticated/donations'
    | '/_authenticated/effectif'
    | '/_authenticated/logs'
    | '/_authenticated/me'
    | '/_authenticated/members'
    | '/_authenticated/objectives'
    | '/_authenticated/pdc'
    | '/_authenticated/points'
    | '/_authenticated/polls'
    | '/_authenticated/profile'
    | '/_authenticated/recruitment'
    | '/_authenticated/staff'
    | '/_authenticated/tools'
    | '/_authenticated/welcome'
    | '/api/health'
    | '/_authenticated/members/$id'
    | '/_authenticated/polls/$id'
    | '/_authenticated/tools/clicker'
    | '/_authenticated/tools/faction'
    | '/_authenticated/tools/leaderboard'
    | '/_authenticated/tools/market'
    | '/_authenticated/tools/player'
    | '/_authenticated/tools/status'
    | '/_authenticated/tools/xp-calculator'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/whoami'
    | '/api/test/login'
    | '/api/test/seed-poll'
    | '/_authenticated/polls/'
    | '/_authenticated/tools/'
    | '/api/public/bot/import'
    | '/api/public/bot/member'
    | '/api/public/bot/message'
    | '/api/public/bot/stats'
    | '/api/public/bot/voice'
    | '/api/public/hooks/paladium-sync'
    | '/api/public/hooks/sync-discord-presence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CandidatureRoute: typeof CandidatureRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthWhoamiRoute: typeof ApiAuthWhoamiRoute
  ApiTestLoginRoute: typeof ApiTestLoginRoute
  ApiTestSeedPollRoute: typeof ApiTestSeedPollRoute
  ApiPublicBotImportRoute: typeof ApiPublicBotImportRoute
  ApiPublicBotMemberRoute: typeof ApiPublicBotMemberRoute
  ApiPublicBotMessageRoute: typeof ApiPublicBotMessageRoute
  ApiPublicBotStatsRoute: typeof ApiPublicBotStatsRoute
  ApiPublicBotVoiceRoute: typeof ApiPublicBotVoiceRoute
  ApiPublicHooksPaladiumSyncRoute: typeof ApiPublicHooksPaladiumSyncRoute
  ApiPublicHooksSyncDiscordPresenceRoute: typeof ApiPublicHooksSyncDiscordPresenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidature': {
      id: '/candidature'
      path: '/candidature'
      fullPath: '/candidature'
      preLoaderRoute: typeof CandidatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recruitment': {
      id: '/_authenticated/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedRecruitmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/polls': {
      id: '/_authenticated/polls'
      path: '/polls'
      fullPath: '/polls'
      preLoaderRoute: typeof AuthenticatedPollsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/points': {
      id: '/_authenticated/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AuthenticatedPointsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdc': {
      id: '/_authenticated/pdc'
      path: '/pdc'
      fullPath: '/pdc'
      preLoaderRoute: typeof AuthenticatedPdcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/objectives': {
      id: '/_authenticated/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof AuthenticatedObjectivesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/effectif': {
      id: '/_authenticated/effectif'
      path: '/effectif'
      fullPath: '/effectif'
      preLoaderRoute: typeof AuthenticatedEffectifRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donations': {
      id: '/_authenticated/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof AuthenticatedDonationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blacklist': {
      id: '/_authenticated/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof AuthenticatedBlacklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/absences': {
      id: '/_authenticated/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AuthenticatedAbsencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/polls/': {
      id: '/_authenticated/polls/'
      path: '/'
      fullPath: '/polls/'
      preLoaderRoute: typeof AuthenticatedPollsIndexRouteImport
      parentRoute: typeof AuthenticatedPollsRoute
    }
    '/api/test/seed-poll': {
      id: '/api/test/seed-poll'
      path: '/api/test/seed-poll'
      fullPath: '/api/test/seed-poll'
      preLoaderRoute: typeof ApiTestSeedPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/login': {
      id: '/api/test/login'
      path: '/api/test/login'
      fullPath: '/api/test/login'
      preLoaderRoute: typeof ApiTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/whoami': {
      id: '/api/auth/whoami'
      path: '/api/auth/whoami'
      fullPath: '/api/auth/whoami'
      preLoaderRoute: typeof ApiAuthWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/xp-calculator': {
      id: '/_authenticated/tools/xp-calculator'
      path: '/xp-calculator'
      fullPath: '/tools/xp-calculator'
      preLoaderRoute: typeof AuthenticatedToolsXpCalculatorRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/status': {
      id: '/_authenticated/tools/status'
      path: '/status'
      fullPath: '/tools/status'
      preLoaderRoute: typeof AuthenticatedToolsStatusRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/player': {
      id: '/_authenticated/tools/player'
      path: '/player'
      fullPath: '/tools/player'
      preLoaderRoute: typeof AuthenticatedToolsPlayerRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/market': {
      id: '/_authenticated/tools/market'
      path: '/market'
      fullPath: '/tools/market'
      preLoaderRoute: typeof AuthenticatedToolsMarketRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/leaderboard': {
      id: '/_authenticated/tools/leaderboard'
      path: '/leaderboard'
      fullPath: '/tools/leaderboard'
      preLoaderRoute: typeof AuthenticatedToolsLeaderboardRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/faction': {
      id: '/_authenticated/tools/faction'
      path: '/faction'
      fullPath: '/tools/faction'
      preLoaderRoute: typeof AuthenticatedToolsFactionRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/clicker': {
      id: '/_authenticated/tools/clicker'
      path: '/clicker'
      fullPath: '/tools/clicker'
      preLoaderRoute: typeof AuthenticatedToolsClickerRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/polls/$id': {
      id: '/_authenticated/polls/$id'
      path: '/$id'
      fullPath: '/polls/$id'
      preLoaderRoute: typeof AuthenticatedPollsIdRouteImport
      parentRoute: typeof AuthenticatedPollsRoute
    }
    '/_authenticated/members/$id': {
      id: '/_authenticated/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AuthenticatedMembersIdRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/api/public/hooks/sync-discord-presence': {
      id: '/api/public/hooks/sync-discord-presence'
      path: '/api/public/hooks/sync-discord-presence'
      fullPath: '/api/public/hooks/sync-discord-presence'
      preLoaderRoute: typeof ApiPublicHooksSyncDiscordPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paladium-sync': {
      id: '/api/public/hooks/paladium-sync'
      path: '/api/public/hooks/paladium-sync'
      fullPath: '/api/public/hooks/paladium-sync'
      preLoaderRoute: typeof ApiPublicHooksPaladiumSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/voice': {
      id: '/api/public/bot/voice'
      path: '/api/public/bot/voice'
      fullPath: '/api/public/bot/voice'
      preLoaderRoute: typeof ApiPublicBotVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/stats': {
      id: '/api/public/bot/stats'
      path: '/api/public/bot/stats'
      fullPath: '/api/public/bot/stats'
      preLoaderRoute: typeof ApiPublicBotStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/message': {
      id: '/api/public/bot/message'
      path: '/api/public/bot/message'
      fullPath: '/api/public/bot/message'
      preLoaderRoute: typeof ApiPublicBotMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/member': {
      id: '/api/public/bot/member'
      path: '/api/public/bot/member'
      fullPath: '/api/public/bot/member'
      preLoaderRoute: typeof ApiPublicBotMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/import': {
      id: '/api/public/bot/import'
      path: '/api/public/bot/import'
      fullPath: '/api/public/bot/import'
      preLoaderRoute: typeof ApiPublicBotImportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersIdRoute: typeof AuthenticatedMembersIdRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersIdRoute: AuthenticatedMembersIdRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedPollsRouteChildren {
  AuthenticatedPollsIdRoute: typeof AuthenticatedPollsIdRoute
  AuthenticatedPollsIndexRoute: typeof AuthenticatedPollsIndexRoute
}

const AuthenticatedPollsRouteChildren: AuthenticatedPollsRouteChildren = {
  AuthenticatedPollsIdRoute: AuthenticatedPollsIdRoute,
  AuthenticatedPollsIndexRoute: AuthenticatedPollsIndexRoute,
}

const AuthenticatedPollsRouteWithChildren =
  AuthenticatedPollsRoute._addFileChildren(AuthenticatedPollsRouteChildren)

interface AuthenticatedToolsRouteChildren {
  AuthenticatedToolsClickerRoute: typeof AuthenticatedToolsClickerRoute
  AuthenticatedToolsFactionRoute: typeof AuthenticatedToolsFactionRoute
  AuthenticatedToolsLeaderboardRoute: typeof AuthenticatedToolsLeaderboardRoute
  AuthenticatedToolsMarketRoute: typeof AuthenticatedToolsMarketRoute
  AuthenticatedToolsPlayerRoute: typeof AuthenticatedToolsPlayerRoute
  AuthenticatedToolsStatusRoute: typeof AuthenticatedToolsStatusRoute
  AuthenticatedToolsXpCalculatorRoute: typeof AuthenticatedToolsXpCalculatorRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
}

const AuthenticatedToolsRouteChildren: AuthenticatedToolsRouteChildren = {
  AuthenticatedToolsClickerRoute: AuthenticatedToolsClickerRoute,
  AuthenticatedToolsFactionRoute: AuthenticatedToolsFactionRoute,
  AuthenticatedToolsLeaderboardRoute: AuthenticatedToolsLeaderboardRoute,
  AuthenticatedToolsMarketRoute: AuthenticatedToolsMarketRoute,
  AuthenticatedToolsPlayerRoute: AuthenticatedToolsPlayerRoute,
  AuthenticatedToolsStatusRoute: AuthenticatedToolsStatusRoute,
  AuthenticatedToolsXpCalculatorRoute: AuthenticatedToolsXpCalculatorRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
}

const AuthenticatedToolsRouteWithChildren =
  AuthenticatedToolsRoute._addFileChildren(AuthenticatedToolsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAbsencesRoute: typeof AuthenticatedAbsencesRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBlacklistRoute: typeof AuthenticatedBlacklistRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDonationsRoute: typeof AuthenticatedDonationsRoute
  AuthenticatedEffectifRoute: typeof AuthenticatedEffectifRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedObjectivesRoute: typeof AuthenticatedObjectivesRoute
  AuthenticatedPdcRoute: typeof AuthenticatedPdcRoute
  AuthenticatedPointsRoute: typeof AuthenticatedPointsRoute
  AuthenticatedPollsRoute: typeof AuthenticatedPollsRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecruitmentRoute: typeof AuthenticatedRecruitmentRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRouteWithChildren
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAbsencesRoute: AuthenticatedAbsencesRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBlacklistRoute: AuthenticatedBlacklistRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDonationsRoute: AuthenticatedDonationsRoute,
  AuthenticatedEffectifRoute: AuthenticatedEffectifRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedObjectivesRoute: AuthenticatedObjectivesRoute,
  AuthenticatedPdcRoute: AuthenticatedPdcRoute,
  AuthenticatedPointsRoute: AuthenticatedPointsRoute,
  AuthenticatedPollsRoute: AuthenticatedPollsRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecruitmentRoute: AuthenticatedRecruitmentRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRouteWithChildren,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CandidatureRoute: CandidatureRoute,
  ForbiddenRoute: ForbiddenRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthWhoamiRoute: ApiAuthWhoamiRoute,
  ApiTestLoginRoute: ApiTestLoginRoute,
  ApiTestSeedPollRoute: ApiTestSeedPollRoute,
  ApiPublicBotImportRoute: ApiPublicBotImportRoute,
  ApiPublicBotMemberRoute: ApiPublicBotMemberRoute,
  ApiPublicBotMessageRoute: ApiPublicBotMessageRoute,
  ApiPublicBotStatsRoute: ApiPublicBotStatsRoute,
  ApiPublicBotVoiceRoute: ApiPublicBotVoiceRoute,
  ApiPublicHooksPaladiumSyncRoute: ApiPublicHooksPaladiumSyncRoute,
  ApiPublicHooksSyncDiscordPresenceRoute:
    ApiPublicHooksSyncDiscordPresenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
