/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as CandidatureRouteImport } from './routes/candidature'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedTrialsRouteImport } from './routes/_authenticated/trials'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedShopRouteImport } from './routes/_authenticated/shop'
import { Route as AuthenticatedRecruitmentRouteImport } from './routes/_authenticated/recruitment'
import { Route as AuthenticatedPointsRouteImport } from './routes/_authenticated/points'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedClassementRouteImport } from './routes/_authenticated/classement'
import { Route as AuthenticatedClassementPointsRouteImport } from './routes/_authenticated/classement-points'
import { Route as AuthenticatedBlacklistRouteImport } from './routes/_authenticated/blacklist'
import { Route as AuthenticatedBacklogRouteImport } from './routes/_authenticated/backlog'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAbsencesRouteImport } from './routes/_authenticated/absences'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as ApiTestSeedPollRouteImport } from './routes/api/test/seed-poll'
import { Route as ApiTestLoginRouteImport } from './routes/api/test/login'
import { Route as ApiPublicMarketRouteImport } from './routes/api/public/market'
import { Route as ApiAuthWhoamiRouteImport } from './routes/api/auth/whoami'
import { Route as ApiAuthTestLoginRouteImport } from './routes/api/auth/test-login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthCallbackRouteImport } from './routes/api/auth/callback'
import { Route as AuthenticatedToolsXpCalculatorRouteImport } from './routes/_authenticated/tools.xp-calculator'
import { Route as AuthenticatedToolsUptimeRouteImport } from './routes/_authenticated/tools.uptime'
import { Route as AuthenticatedToolsStatusRouteImport } from './routes/_authenticated/tools.status'
import { Route as AuthenticatedToolsShopAdminRouteImport } from './routes/_authenticated/tools.shop-admin'
import { Route as AuthenticatedToolsSalesRouteImport } from './routes/_authenticated/tools.sales'
import { Route as AuthenticatedToolsPlayerRouteImport } from './routes/_authenticated/tools.player'
import { Route as AuthenticatedToolsMarketRouteImport } from './routes/_authenticated/tools.market'
import { Route as AuthenticatedToolsLeaderboardRouteImport } from './routes/_authenticated/tools.leaderboard'
import { Route as AuthenticatedToolsFactionRouteImport } from './routes/_authenticated/tools.faction'
import { Route as AuthenticatedToolsEventsRouteImport } from './routes/_authenticated/tools.events'
import { Route as AuthenticatedToolsClickerRouteImport } from './routes/_authenticated/tools.clicker'
import { Route as AuthenticatedToolsAlertsRouteImport } from './routes/_authenticated/tools.alerts'
import { Route as AuthenticatedStaffAppealsRouteImport } from './routes/_authenticated/staff.appeals'
import { Route as AuthenticatedStaffAnnounceRouteImport } from './routes/_authenticated/staff.announce'
import { Route as AuthenticatedMembersIdRouteImport } from './routes/_authenticated/members.$id'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as ApiPublicHooksVerifyAuditChainRouteImport } from './routes/api/public/hooks/verify-audit-chain'
import { Route as ApiPublicHooksSyncDiscordPresenceRouteImport } from './routes/api/public/hooks/sync-discord-presence'
import { Route as ApiPublicHooksScanAnomaliesRouteImport } from './routes/api/public/hooks/scan-anomalies'
import { Route as ApiPublicHooksRunAutomationRouteImport } from './routes/api/public/hooks/run-automation'
import { Route as ApiPublicHooksProcessApplicationReviewsRouteImport } from './routes/api/public/hooks/process-application-reviews'
import { Route as ApiPublicHooksPaladiumSyncRouteImport } from './routes/api/public/hooks/paladium-sync'
import { Route as ApiPublicHooksPaladiumStatusSyncRouteImport } from './routes/api/public/hooks/paladium-status-sync'
import { Route as ApiPublicHooksPaladiumMarketSyncRouteImport } from './routes/api/public/hooks/paladium-market-sync'
import { Route as ApiPublicHooksPaladiumFactionSyncRouteImport } from './routes/api/public/hooks/paladium-faction-sync'
import { Route as ApiPublicHooksPaladiumAdminShopSyncRouteImport } from './routes/api/public/hooks/paladium-admin-shop-sync'
import { Route as ApiPublicHooksImportMcStatsRouteImport } from './routes/api/public/hooks/import-mc-stats'
import { Route as ApiPublicHooksGenerateSalaryPreviewRouteImport } from './routes/api/public/hooks/generate-salary-preview'
import { Route as ApiPublicHooksGenerateDigestRouteImport } from './routes/api/public/hooks/generate-digest'
import { Route as ApiPublicBotVoiceRouteImport } from './routes/api/public/bot/voice'
import { Route as ApiPublicBotStatsRouteImport } from './routes/api/public/bot/stats'
import { Route as ApiPublicBotMessageRouteImport } from './routes/api/public/bot/message'
import { Route as ApiPublicBotMemberRouteImport } from './routes/api/public/bot/member'
import { Route as ApiPublicBotMcLinkConfirmRouteImport } from './routes/api/public/bot/mc-link-confirm'
import { Route as ApiPublicBotImportRouteImport } from './routes/api/public/bot/import'
import { Route as ApiStaffMembersIdWarningsRouteImport } from './routes/api/staff/members.$id.warnings'
import { Route as ApiStaffMembersIdNotesRouteImport } from './routes/api/staff/members.$id.notes'
import { Route as ApiPublicBotQueryProfilRouteImport } from './routes/api/public/bot/query/profil'
import { Route as ApiPublicBotQueryPointsRouteImport } from './routes/api/public/bot/query/points'
import { Route as ApiPublicBotQueryDonValiderRouteImport } from './routes/api/public/bot/query/don-valider'
import { Route as ApiPublicBotQueryCandidaturesRouteImport } from './routes/api/public/bot/query/candidatures'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatureRoute = CandidatureRouteImport.update({
  id: '/candidature',
  path: '/candidature',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrialsRoute = AuthenticatedTrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/staff.lazy').then((d) => d.Route),
)
const AuthenticatedShopRoute = AuthenticatedShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecruitmentRoute =
  AuthenticatedRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPointsRoute = AuthenticatedPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassementRoute = AuthenticatedClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClassementPointsRoute =
  AuthenticatedClassementPointsRouteImport.update({
    id: '/classement-points',
    path: '/classement-points',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlacklistRoute = AuthenticatedBlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacklogRoute = AuthenticatedBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAbsencesRoute = AuthenticatedAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedToolsRoute,
} as any)
const ApiTestSeedPollRoute = ApiTestSeedPollRouteImport.update({
  id: '/api/test/seed-poll',
  path: '/api/test/seed-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestLoginRoute = ApiTestLoginRouteImport.update({
  id: '/api/test/login',
  path: '/api/test/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMarketRoute = ApiPublicMarketRouteImport.update({
  id: '/api/public/market',
  path: '/api/public/market',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthWhoamiRoute = ApiAuthWhoamiRouteImport.update({
  id: '/api/auth/whoami',
  path: '/api/auth/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTestLoginRoute = ApiAuthTestLoginRouteImport.update({
  id: '/api/auth/test-login',
  path: '/api/auth/test-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsXpCalculatorRoute =
  AuthenticatedToolsXpCalculatorRouteImport.update({
    id: '/xp-calculator',
    path: '/xp-calculator',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsUptimeRoute =
  AuthenticatedToolsUptimeRouteImport.update({
    id: '/uptime',
    path: '/uptime',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsStatusRoute =
  AuthenticatedToolsStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsShopAdminRoute =
  AuthenticatedToolsShopAdminRouteImport.update({
    id: '/shop-admin',
    path: '/shop-admin',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsSalesRoute = AuthenticatedToolsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedToolsRoute,
} as any)
const AuthenticatedToolsPlayerRoute =
  AuthenticatedToolsPlayerRouteImport.update({
    id: '/player',
    path: '/player',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsMarketRoute =
  AuthenticatedToolsMarketRouteImport.update({
    id: '/market',
    path: '/market',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsLeaderboardRoute =
  AuthenticatedToolsLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsFactionRoute =
  AuthenticatedToolsFactionRouteImport.update({
    id: '/faction',
    path: '/faction',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsEventsRoute =
  AuthenticatedToolsEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsClickerRoute =
  AuthenticatedToolsClickerRouteImport.update({
    id: '/clicker',
    path: '/clicker',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedToolsAlertsRoute =
  AuthenticatedToolsAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedStaffAppealsRoute =
  AuthenticatedStaffAppealsRouteImport.update({
    id: '/appeals',
    path: '/appeals',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffAnnounceRoute =
  AuthenticatedStaffAnnounceRouteImport.update({
    id: '/announce',
    path: '/announce',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedMembersIdRoute = AuthenticatedMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMembersRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHooksVerifyAuditChainRoute =
  ApiPublicHooksVerifyAuditChainRouteImport.update({
    id: '/api/public/hooks/verify-audit-chain',
    path: '/api/public/hooks/verify-audit-chain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncDiscordPresenceRoute =
  ApiPublicHooksSyncDiscordPresenceRouteImport.update({
    id: '/api/public/hooks/sync-discord-presence',
    path: '/api/public/hooks/sync-discord-presence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScanAnomaliesRoute =
  ApiPublicHooksScanAnomaliesRouteImport.update({
    id: '/api/public/hooks/scan-anomalies',
    path: '/api/public/hooks/scan-anomalies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRunAutomationRoute =
  ApiPublicHooksRunAutomationRouteImport.update({
    id: '/api/public/hooks/run-automation',
    path: '/api/public/hooks/run-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessApplicationReviewsRoute =
  ApiPublicHooksProcessApplicationReviewsRouteImport.update({
    id: '/api/public/hooks/process-application-reviews',
    path: '/api/public/hooks/process-application-reviews',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaladiumSyncRoute =
  ApiPublicHooksPaladiumSyncRouteImport.update({
    id: '/api/public/hooks/paladium-sync',
    path: '/api/public/hooks/paladium-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaladiumStatusSyncRoute =
  ApiPublicHooksPaladiumStatusSyncRouteImport.update({
    id: '/api/public/hooks/paladium-status-sync',
    path: '/api/public/hooks/paladium-status-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaladiumMarketSyncRoute =
  ApiPublicHooksPaladiumMarketSyncRouteImport.update({
    id: '/api/public/hooks/paladium-market-sync',
    path: '/api/public/hooks/paladium-market-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaladiumFactionSyncRoute =
  ApiPublicHooksPaladiumFactionSyncRouteImport.update({
    id: '/api/public/hooks/paladium-faction-sync',
    path: '/api/public/hooks/paladium-faction-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPaladiumAdminShopSyncRoute =
  ApiPublicHooksPaladiumAdminShopSyncRouteImport.update({
    id: '/api/public/hooks/paladium-admin-shop-sync',
    path: '/api/public/hooks/paladium-admin-shop-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksImportMcStatsRoute =
  ApiPublicHooksImportMcStatsRouteImport.update({
    id: '/api/public/hooks/import-mc-stats',
    path: '/api/public/hooks/import-mc-stats',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateSalaryPreviewRoute =
  ApiPublicHooksGenerateSalaryPreviewRouteImport.update({
    id: '/api/public/hooks/generate-salary-preview',
    path: '/api/public/hooks/generate-salary-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGenerateDigestRoute =
  ApiPublicHooksGenerateDigestRouteImport.update({
    id: '/api/public/hooks/generate-digest',
    path: '/api/public/hooks/generate-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotVoiceRoute = ApiPublicBotVoiceRouteImport.update({
  id: '/api/public/bot/voice',
  path: '/api/public/bot/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotStatsRoute = ApiPublicBotStatsRouteImport.update({
  id: '/api/public/bot/stats',
  path: '/api/public/bot/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotMessageRoute = ApiPublicBotMessageRouteImport.update({
  id: '/api/public/bot/message',
  path: '/api/public/bot/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotMemberRoute = ApiPublicBotMemberRouteImport.update({
  id: '/api/public/bot/member',
  path: '/api/public/bot/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotMcLinkConfirmRoute =
  ApiPublicBotMcLinkConfirmRouteImport.update({
    id: '/api/public/bot/mc-link-confirm',
    path: '/api/public/bot/mc-link-confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotImportRoute = ApiPublicBotImportRouteImport.update({
  id: '/api/public/bot/import',
  path: '/api/public/bot/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffMembersIdWarningsRoute =
  ApiStaffMembersIdWarningsRouteImport.update({
    id: '/api/staff/members/$id/warnings',
    path: '/api/staff/members/$id/warnings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaffMembersIdNotesRoute = ApiStaffMembersIdNotesRouteImport.update({
  id: '/api/staff/members/$id/notes',
  path: '/api/staff/members/$id/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotQueryProfilRoute = ApiPublicBotQueryProfilRouteImport.update({
  id: '/api/public/bot/query/profil',
  path: '/api/public/bot/query/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotQueryPointsRoute = ApiPublicBotQueryPointsRouteImport.update({
  id: '/api/public/bot/query/points',
  path: '/api/public/bot/query/points',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotQueryDonValiderRoute =
  ApiPublicBotQueryDonValiderRouteImport.update({
    id: '/api/public/bot/query/don-valider',
    path: '/api/public/bot/query/don-valider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBotQueryCandidaturesRoute =
  ApiPublicBotQueryCandidaturesRouteImport.update({
    id: '/api/public/bot/query/candidatures',
    path: '/api/public/bot/query/candidatures',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidature': typeof CandidatureRoute
  '/forbidden': typeof ForbiddenRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/classement-points': typeof AuthenticatedClassementPointsRoute
  '/config': typeof AuthenticatedConfigRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/me': typeof AuthenticatedMeRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/points': typeof AuthenticatedPointsRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/shop': typeof AuthenticatedShopRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/trials': typeof AuthenticatedTrialsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/staff/announce': typeof AuthenticatedStaffAnnounceRoute
  '/staff/appeals': typeof AuthenticatedStaffAppealsRoute
  '/tools/alerts': typeof AuthenticatedToolsAlertsRoute
  '/tools/clicker': typeof AuthenticatedToolsClickerRoute
  '/tools/events': typeof AuthenticatedToolsEventsRoute
  '/tools/faction': typeof AuthenticatedToolsFactionRoute
  '/tools/leaderboard': typeof AuthenticatedToolsLeaderboardRoute
  '/tools/market': typeof AuthenticatedToolsMarketRoute
  '/tools/player': typeof AuthenticatedToolsPlayerRoute
  '/tools/sales': typeof AuthenticatedToolsSalesRoute
  '/tools/shop-admin': typeof AuthenticatedToolsShopAdminRoute
  '/tools/status': typeof AuthenticatedToolsStatusRoute
  '/tools/uptime': typeof AuthenticatedToolsUptimeRoute
  '/tools/xp-calculator': typeof AuthenticatedToolsXpCalculatorRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/api/auth/whoami': typeof ApiAuthWhoamiRoute
  '/api/public/market': typeof ApiPublicMarketRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/seed-poll': typeof ApiTestSeedPollRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/api/public/bot/import': typeof ApiPublicBotImportRoute
  '/api/public/bot/mc-link-confirm': typeof ApiPublicBotMcLinkConfirmRoute
  '/api/public/bot/member': typeof ApiPublicBotMemberRoute
  '/api/public/bot/message': typeof ApiPublicBotMessageRoute
  '/api/public/bot/stats': typeof ApiPublicBotStatsRoute
  '/api/public/bot/voice': typeof ApiPublicBotVoiceRoute
  '/api/public/hooks/generate-digest': typeof ApiPublicHooksGenerateDigestRoute
  '/api/public/hooks/generate-salary-preview': typeof ApiPublicHooksGenerateSalaryPreviewRoute
  '/api/public/hooks/import-mc-stats': typeof ApiPublicHooksImportMcStatsRoute
  '/api/public/hooks/paladium-admin-shop-sync': typeof ApiPublicHooksPaladiumAdminShopSyncRoute
  '/api/public/hooks/paladium-faction-sync': typeof ApiPublicHooksPaladiumFactionSyncRoute
  '/api/public/hooks/paladium-market-sync': typeof ApiPublicHooksPaladiumMarketSyncRoute
  '/api/public/hooks/paladium-status-sync': typeof ApiPublicHooksPaladiumStatusSyncRoute
  '/api/public/hooks/paladium-sync': typeof ApiPublicHooksPaladiumSyncRoute
  '/api/public/hooks/process-application-reviews': typeof ApiPublicHooksProcessApplicationReviewsRoute
  '/api/public/hooks/run-automation': typeof ApiPublicHooksRunAutomationRoute
  '/api/public/hooks/scan-anomalies': typeof ApiPublicHooksScanAnomaliesRoute
  '/api/public/hooks/sync-discord-presence': typeof ApiPublicHooksSyncDiscordPresenceRoute
  '/api/public/hooks/verify-audit-chain': typeof ApiPublicHooksVerifyAuditChainRoute
  '/api/public/bot/query/candidatures': typeof ApiPublicBotQueryCandidaturesRoute
  '/api/public/bot/query/don-valider': typeof ApiPublicBotQueryDonValiderRoute
  '/api/public/bot/query/points': typeof ApiPublicBotQueryPointsRoute
  '/api/public/bot/query/profil': typeof ApiPublicBotQueryProfilRoute
  '/api/staff/members/$id/notes': typeof ApiStaffMembersIdNotesRoute
  '/api/staff/members/$id/warnings': typeof ApiStaffMembersIdWarningsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidature': typeof CandidatureRoute
  '/forbidden': typeof ForbiddenRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assistant': typeof AuthenticatedAssistantRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/classement': typeof AuthenticatedClassementRoute
  '/classement-points': typeof AuthenticatedClassementPointsRoute
  '/config': typeof AuthenticatedConfigRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/me': typeof AuthenticatedMeRoute
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/points': typeof AuthenticatedPointsRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/shop': typeof AuthenticatedShopRoute
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/trials': typeof AuthenticatedTrialsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/staff/announce': typeof AuthenticatedStaffAnnounceRoute
  '/staff/appeals': typeof AuthenticatedStaffAppealsRoute
  '/tools/alerts': typeof AuthenticatedToolsAlertsRoute
  '/tools/clicker': typeof AuthenticatedToolsClickerRoute
  '/tools/events': typeof AuthenticatedToolsEventsRoute
  '/tools/faction': typeof AuthenticatedToolsFactionRoute
  '/tools/leaderboard': typeof AuthenticatedToolsLeaderboardRoute
  '/tools/market': typeof AuthenticatedToolsMarketRoute
  '/tools/player': typeof AuthenticatedToolsPlayerRoute
  '/tools/sales': typeof AuthenticatedToolsSalesRoute
  '/tools/shop-admin': typeof AuthenticatedToolsShopAdminRoute
  '/tools/status': typeof AuthenticatedToolsStatusRoute
  '/tools/uptime': typeof AuthenticatedToolsUptimeRoute
  '/tools/xp-calculator': typeof AuthenticatedToolsXpCalculatorRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/api/auth/whoami': typeof ApiAuthWhoamiRoute
  '/api/public/market': typeof ApiPublicMarketRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/seed-poll': typeof ApiTestSeedPollRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/api/public/bot/import': typeof ApiPublicBotImportRoute
  '/api/public/bot/mc-link-confirm': typeof ApiPublicBotMcLinkConfirmRoute
  '/api/public/bot/member': typeof ApiPublicBotMemberRoute
  '/api/public/bot/message': typeof ApiPublicBotMessageRoute
  '/api/public/bot/stats': typeof ApiPublicBotStatsRoute
  '/api/public/bot/voice': typeof ApiPublicBotVoiceRoute
  '/api/public/hooks/generate-digest': typeof ApiPublicHooksGenerateDigestRoute
  '/api/public/hooks/generate-salary-preview': typeof ApiPublicHooksGenerateSalaryPreviewRoute
  '/api/public/hooks/import-mc-stats': typeof ApiPublicHooksImportMcStatsRoute
  '/api/public/hooks/paladium-admin-shop-sync': typeof ApiPublicHooksPaladiumAdminShopSyncRoute
  '/api/public/hooks/paladium-faction-sync': typeof ApiPublicHooksPaladiumFactionSyncRoute
  '/api/public/hooks/paladium-market-sync': typeof ApiPublicHooksPaladiumMarketSyncRoute
  '/api/public/hooks/paladium-status-sync': typeof ApiPublicHooksPaladiumStatusSyncRoute
  '/api/public/hooks/paladium-sync': typeof ApiPublicHooksPaladiumSyncRoute
  '/api/public/hooks/process-application-reviews': typeof ApiPublicHooksProcessApplicationReviewsRoute
  '/api/public/hooks/run-automation': typeof ApiPublicHooksRunAutomationRoute
  '/api/public/hooks/scan-anomalies': typeof ApiPublicHooksScanAnomaliesRoute
  '/api/public/hooks/sync-discord-presence': typeof ApiPublicHooksSyncDiscordPresenceRoute
  '/api/public/hooks/verify-audit-chain': typeof ApiPublicHooksVerifyAuditChainRoute
  '/api/public/bot/query/candidatures': typeof ApiPublicBotQueryCandidaturesRoute
  '/api/public/bot/query/don-valider': typeof ApiPublicBotQueryDonValiderRoute
  '/api/public/bot/query/points': typeof ApiPublicBotQueryPointsRoute
  '/api/public/bot/query/profil': typeof ApiPublicBotQueryProfilRoute
  '/api/staff/members/$id/notes': typeof ApiStaffMembersIdNotesRoute
  '/api/staff/members/$id/warnings': typeof ApiStaffMembersIdWarningsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/candidature': typeof CandidatureRoute
  '/forbidden': typeof ForbiddenRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/_authenticated/absences': typeof AuthenticatedAbsencesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/backlog': typeof AuthenticatedBacklogRoute
  '/_authenticated/blacklist': typeof AuthenticatedBlacklistRoute
  '/_authenticated/classement': typeof AuthenticatedClassementRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/points': typeof AuthenticatedPointsRoute
  '/_authenticated/recruitment': typeof AuthenticatedRecruitmentRoute
  '/_authenticated/shop': typeof AuthenticatedShopRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/tools': typeof AuthenticatedToolsRouteWithChildren
  '/_authenticated/trials': typeof AuthenticatedTrialsRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/api/health': typeof ApiHealthRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/members/$id': typeof AuthenticatedMembersIdRoute
  '/_authenticated/staff/announce': typeof AuthenticatedStaffAnnounceRoute
  '/_authenticated/staff/appeals': typeof AuthenticatedStaffAppealsRoute
  '/_authenticated/tools/alerts': typeof AuthenticatedToolsAlertsRoute
  '/_authenticated/tools/clicker': typeof AuthenticatedToolsClickerRoute
  '/_authenticated/tools/events': typeof AuthenticatedToolsEventsRoute
  '/_authenticated/tools/faction': typeof AuthenticatedToolsFactionRoute
  '/_authenticated/tools/leaderboard': typeof AuthenticatedToolsLeaderboardRoute
  '/_authenticated/tools/market': typeof AuthenticatedToolsMarketRoute
  '/_authenticated/tools/player': typeof AuthenticatedToolsPlayerRoute
  '/_authenticated/tools/sales': typeof AuthenticatedToolsSalesRoute
  '/_authenticated/tools/shop-admin': typeof AuthenticatedToolsShopAdminRoute
  '/_authenticated/tools/status': typeof AuthenticatedToolsStatusRoute
  '/_authenticated/tools/uptime': typeof AuthenticatedToolsUptimeRoute
  '/_authenticated/tools/xp-calculator': typeof AuthenticatedToolsXpCalculatorRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/test-login': typeof ApiAuthTestLoginRoute
  '/api/auth/whoami': typeof ApiAuthWhoamiRoute
  '/api/public/market': typeof ApiPublicMarketRoute
  '/api/test/login': typeof ApiTestLoginRoute
  '/api/test/seed-poll': typeof ApiTestSeedPollRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/api/public/bot/import': typeof ApiPublicBotImportRoute
  '/api/public/bot/mc-link-confirm': typeof ApiPublicBotMcLinkConfirmRoute
  '/api/public/bot/member': typeof ApiPublicBotMemberRoute
  '/api/public/bot/message': typeof ApiPublicBotMessageRoute
  '/api/public/bot/stats': typeof ApiPublicBotStatsRoute
  '/api/public/bot/voice': typeof ApiPublicBotVoiceRoute
  '/api/public/hooks/generate-digest': typeof ApiPublicHooksGenerateDigestRoute
  '/api/public/hooks/generate-salary-preview': typeof ApiPublicHooksGenerateSalaryPreviewRoute
  '/api/public/hooks/import-mc-stats': typeof ApiPublicHooksImportMcStatsRoute
  '/api/public/hooks/paladium-admin-shop-sync': typeof ApiPublicHooksPaladiumAdminShopSyncRoute
  '/api/public/hooks/paladium-faction-sync': typeof ApiPublicHooksPaladiumFactionSyncRoute
  '/api/public/hooks/paladium-market-sync': typeof ApiPublicHooksPaladiumMarketSyncRoute
  '/api/public/hooks/paladium-status-sync': typeof ApiPublicHooksPaladiumStatusSyncRoute
  '/api/public/hooks/paladium-sync': typeof ApiPublicHooksPaladiumSyncRoute
  '/api/public/hooks/process-application-reviews': typeof ApiPublicHooksProcessApplicationReviewsRoute
  '/api/public/hooks/run-automation': typeof ApiPublicHooksRunAutomationRoute
  '/api/public/hooks/scan-anomalies': typeof ApiPublicHooksScanAnomaliesRoute
  '/api/public/hooks/sync-discord-presence': typeof ApiPublicHooksSyncDiscordPresenceRoute
  '/api/public/hooks/verify-audit-chain': typeof ApiPublicHooksVerifyAuditChainRoute
  '/api/public/bot/query/candidatures': typeof ApiPublicBotQueryCandidaturesRoute
  '/api/public/bot/query/don-valider': typeof ApiPublicBotQueryDonValiderRoute
  '/api/public/bot/query/points': typeof ApiPublicBotQueryPointsRoute
  '/api/public/bot/query/profil': typeof ApiPublicBotQueryProfilRoute
  '/api/staff/members/$id/notes': typeof ApiStaffMembersIdNotesRoute
  '/api/staff/members/$id/warnings': typeof ApiStaffMembersIdWarningsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidature'
    | '/forbidden'
    | '/legal'
    | '/login'
    | '/absences'
    | '/admin'
    | '/assistant'
    | '/backlog'
    | '/blacklist'
    | '/classement'
    | '/classement-points'
    | '/config'
    | '/logs'
    | '/me'
    | '/members'
    | '/points'
    | '/recruitment'
    | '/shop'
    | '/staff'
    | '/tools'
    | '/trials'
    | '/welcome'
    | '/api/health'
    | '/admin/audit'
    | '/members/$id'
    | '/staff/announce'
    | '/staff/appeals'
    | '/tools/alerts'
    | '/tools/clicker'
    | '/tools/events'
    | '/tools/faction'
    | '/tools/leaderboard'
    | '/tools/market'
    | '/tools/player'
    | '/tools/sales'
    | '/tools/shop-admin'
    | '/tools/status'
    | '/tools/uptime'
    | '/tools/xp-calculator'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/test-login'
    | '/api/auth/whoami'
    | '/api/public/market'
    | '/api/test/login'
    | '/api/test/seed-poll'
    | '/tools/'
    | '/api/public/bot/import'
    | '/api/public/bot/mc-link-confirm'
    | '/api/public/bot/member'
    | '/api/public/bot/message'
    | '/api/public/bot/stats'
    | '/api/public/bot/voice'
    | '/api/public/hooks/generate-digest'
    | '/api/public/hooks/generate-salary-preview'
    | '/api/public/hooks/import-mc-stats'
    | '/api/public/hooks/paladium-admin-shop-sync'
    | '/api/public/hooks/paladium-faction-sync'
    | '/api/public/hooks/paladium-market-sync'
    | '/api/public/hooks/paladium-status-sync'
    | '/api/public/hooks/paladium-sync'
    | '/api/public/hooks/process-application-reviews'
    | '/api/public/hooks/run-automation'
    | '/api/public/hooks/scan-anomalies'
    | '/api/public/hooks/sync-discord-presence'
    | '/api/public/hooks/verify-audit-chain'
    | '/api/public/bot/query/candidatures'
    | '/api/public/bot/query/don-valider'
    | '/api/public/bot/query/points'
    | '/api/public/bot/query/profil'
    | '/api/staff/members/$id/notes'
    | '/api/staff/members/$id/warnings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidature'
    | '/forbidden'
    | '/legal'
    | '/login'
    | '/absences'
    | '/admin'
    | '/assistant'
    | '/backlog'
    | '/blacklist'
    | '/classement'
    | '/classement-points'
    | '/config'
    | '/logs'
    | '/me'
    | '/members'
    | '/points'
    | '/recruitment'
    | '/shop'
    | '/staff'
    | '/trials'
    | '/welcome'
    | '/api/health'
    | '/admin/audit'
    | '/members/$id'
    | '/staff/announce'
    | '/staff/appeals'
    | '/tools/alerts'
    | '/tools/clicker'
    | '/tools/events'
    | '/tools/faction'
    | '/tools/leaderboard'
    | '/tools/market'
    | '/tools/player'
    | '/tools/sales'
    | '/tools/shop-admin'
    | '/tools/status'
    | '/tools/uptime'
    | '/tools/xp-calculator'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/test-login'
    | '/api/auth/whoami'
    | '/api/public/market'
    | '/api/test/login'
    | '/api/test/seed-poll'
    | '/tools'
    | '/api/public/bot/import'
    | '/api/public/bot/mc-link-confirm'
    | '/api/public/bot/member'
    | '/api/public/bot/message'
    | '/api/public/bot/stats'
    | '/api/public/bot/voice'
    | '/api/public/hooks/generate-digest'
    | '/api/public/hooks/generate-salary-preview'
    | '/api/public/hooks/import-mc-stats'
    | '/api/public/hooks/paladium-admin-shop-sync'
    | '/api/public/hooks/paladium-faction-sync'
    | '/api/public/hooks/paladium-market-sync'
    | '/api/public/hooks/paladium-status-sync'
    | '/api/public/hooks/paladium-sync'
    | '/api/public/hooks/process-application-reviews'
    | '/api/public/hooks/run-automation'
    | '/api/public/hooks/scan-anomalies'
    | '/api/public/hooks/sync-discord-presence'
    | '/api/public/hooks/verify-audit-chain'
    | '/api/public/bot/query/candidatures'
    | '/api/public/bot/query/don-valider'
    | '/api/public/bot/query/points'
    | '/api/public/bot/query/profil'
    | '/api/staff/members/$id/notes'
    | '/api/staff/members/$id/warnings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/candidature'
    | '/forbidden'
    | '/legal'
    | '/login'
    | '/_authenticated/absences'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/backlog'
    | '/_authenticated/blacklist'
    | '/_authenticated/classement'
    | '/_authenticated/classement-points'
    | '/_authenticated/config'
    | '/_authenticated/logs'
    | '/_authenticated/me'
    | '/_authenticated/members'
    | '/_authenticated/points'
    | '/_authenticated/recruitment'
    | '/_authenticated/shop'
    | '/_authenticated/staff'
    | '/_authenticated/tools'
    | '/_authenticated/trials'
    | '/_authenticated/welcome'
    | '/api/health'
    | '/_authenticated/admin/audit'
    | '/_authenticated/members/$id'
    | '/_authenticated/staff/announce'
    | '/_authenticated/staff/appeals'
    | '/_authenticated/tools/alerts'
    | '/_authenticated/tools/clicker'
    | '/_authenticated/tools/events'
    | '/_authenticated/tools/faction'
    | '/_authenticated/tools/leaderboard'
    | '/_authenticated/tools/market'
    | '/_authenticated/tools/player'
    | '/_authenticated/tools/sales'
    | '/_authenticated/tools/shop-admin'
    | '/_authenticated/tools/status'
    | '/_authenticated/tools/uptime'
    | '/_authenticated/tools/xp-calculator'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/test-login'
    | '/api/auth/whoami'
    | '/api/public/market'
    | '/api/test/login'
    | '/api/test/seed-poll'
    | '/_authenticated/tools/'
    | '/api/public/bot/import'
    | '/api/public/bot/mc-link-confirm'
    | '/api/public/bot/member'
    | '/api/public/bot/message'
    | '/api/public/bot/stats'
    | '/api/public/bot/voice'
    | '/api/public/hooks/generate-digest'
    | '/api/public/hooks/generate-salary-preview'
    | '/api/public/hooks/import-mc-stats'
    | '/api/public/hooks/paladium-admin-shop-sync'
    | '/api/public/hooks/paladium-faction-sync'
    | '/api/public/hooks/paladium-market-sync'
    | '/api/public/hooks/paladium-status-sync'
    | '/api/public/hooks/paladium-sync'
    | '/api/public/hooks/process-application-reviews'
    | '/api/public/hooks/run-automation'
    | '/api/public/hooks/scan-anomalies'
    | '/api/public/hooks/sync-discord-presence'
    | '/api/public/hooks/verify-audit-chain'
    | '/api/public/bot/query/candidatures'
    | '/api/public/bot/query/don-valider'
    | '/api/public/bot/query/points'
    | '/api/public/bot/query/profil'
    | '/api/staff/members/$id/notes'
    | '/api/staff/members/$id/warnings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CandidatureRoute: typeof CandidatureRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthTestLoginRoute: typeof ApiAuthTestLoginRoute
  ApiAuthWhoamiRoute: typeof ApiAuthWhoamiRoute
  ApiPublicMarketRoute: typeof ApiPublicMarketRoute
  ApiTestLoginRoute: typeof ApiTestLoginRoute
  ApiTestSeedPollRoute: typeof ApiTestSeedPollRoute
  ApiPublicBotImportRoute: typeof ApiPublicBotImportRoute
  ApiPublicBotMcLinkConfirmRoute: typeof ApiPublicBotMcLinkConfirmRoute
  ApiPublicBotMemberRoute: typeof ApiPublicBotMemberRoute
  ApiPublicBotMessageRoute: typeof ApiPublicBotMessageRoute
  ApiPublicBotStatsRoute: typeof ApiPublicBotStatsRoute
  ApiPublicBotVoiceRoute: typeof ApiPublicBotVoiceRoute
  ApiPublicHooksGenerateDigestRoute: typeof ApiPublicHooksGenerateDigestRoute
  ApiPublicHooksGenerateSalaryPreviewRoute: typeof ApiPublicHooksGenerateSalaryPreviewRoute
  ApiPublicHooksImportMcStatsRoute: typeof ApiPublicHooksImportMcStatsRoute
  ApiPublicHooksPaladiumAdminShopSyncRoute: typeof ApiPublicHooksPaladiumAdminShopSyncRoute
  ApiPublicHooksPaladiumFactionSyncRoute: typeof ApiPublicHooksPaladiumFactionSyncRoute
  ApiPublicHooksPaladiumMarketSyncRoute: typeof ApiPublicHooksPaladiumMarketSyncRoute
  ApiPublicHooksPaladiumStatusSyncRoute: typeof ApiPublicHooksPaladiumStatusSyncRoute
  ApiPublicHooksPaladiumSyncRoute: typeof ApiPublicHooksPaladiumSyncRoute
  ApiPublicHooksProcessApplicationReviewsRoute: typeof ApiPublicHooksProcessApplicationReviewsRoute
  ApiPublicHooksRunAutomationRoute: typeof ApiPublicHooksRunAutomationRoute
  ApiPublicHooksScanAnomaliesRoute: typeof ApiPublicHooksScanAnomaliesRoute
  ApiPublicHooksSyncDiscordPresenceRoute: typeof ApiPublicHooksSyncDiscordPresenceRoute
  ApiPublicHooksVerifyAuditChainRoute: typeof ApiPublicHooksVerifyAuditChainRoute
  ApiPublicBotQueryCandidaturesRoute: typeof ApiPublicBotQueryCandidaturesRoute
  ApiPublicBotQueryDonValiderRoute: typeof ApiPublicBotQueryDonValiderRoute
  ApiPublicBotQueryPointsRoute: typeof ApiPublicBotQueryPointsRoute
  ApiPublicBotQueryProfilRoute: typeof ApiPublicBotQueryProfilRoute
  ApiStaffMembersIdNotesRoute: typeof ApiStaffMembersIdNotesRoute
  ApiStaffMembersIdWarningsRoute: typeof ApiStaffMembersIdWarningsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidature': {
      id: '/candidature'
      path: '/candidature'
      fullPath: '/candidature'
      preLoaderRoute: typeof CandidatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trials': {
      id: '/_authenticated/trials'
      path: '/trials'
      fullPath: '/trials'
      preLoaderRoute: typeof AuthenticatedTrialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shop': {
      id: '/_authenticated/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AuthenticatedShopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recruitment': {
      id: '/_authenticated/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedRecruitmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/points': {
      id: '/_authenticated/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof AuthenticatedPointsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classement': {
      id: '/_authenticated/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof AuthenticatedClassementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classement-points': {
      id: '/_authenticated/classement-points'
      path: '/classement-points'
      fullPath: '/classement-points'
      preLoaderRoute: typeof AuthenticatedClassementPointsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blacklist': {
      id: '/_authenticated/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof AuthenticatedBlacklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backlog': {
      id: '/_authenticated/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AuthenticatedBacklogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/absences': {
      id: '/_authenticated/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AuthenticatedAbsencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/api/test/seed-poll': {
      id: '/api/test/seed-poll'
      path: '/api/test/seed-poll'
      fullPath: '/api/test/seed-poll'
      preLoaderRoute: typeof ApiTestSeedPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/login': {
      id: '/api/test/login'
      path: '/api/test/login'
      fullPath: '/api/test/login'
      preLoaderRoute: typeof ApiTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/market': {
      id: '/api/public/market'
      path: '/api/public/market'
      fullPath: '/api/public/market'
      preLoaderRoute: typeof ApiPublicMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/whoami': {
      id: '/api/auth/whoami'
      path: '/api/auth/whoami'
      fullPath: '/api/auth/whoami'
      preLoaderRoute: typeof ApiAuthWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/test-login': {
      id: '/api/auth/test-login'
      path: '/api/auth/test-login'
      fullPath: '/api/auth/test-login'
      preLoaderRoute: typeof ApiAuthTestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/xp-calculator': {
      id: '/_authenticated/tools/xp-calculator'
      path: '/xp-calculator'
      fullPath: '/tools/xp-calculator'
      preLoaderRoute: typeof AuthenticatedToolsXpCalculatorRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/uptime': {
      id: '/_authenticated/tools/uptime'
      path: '/uptime'
      fullPath: '/tools/uptime'
      preLoaderRoute: typeof AuthenticatedToolsUptimeRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/status': {
      id: '/_authenticated/tools/status'
      path: '/status'
      fullPath: '/tools/status'
      preLoaderRoute: typeof AuthenticatedToolsStatusRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/shop-admin': {
      id: '/_authenticated/tools/shop-admin'
      path: '/shop-admin'
      fullPath: '/tools/shop-admin'
      preLoaderRoute: typeof AuthenticatedToolsShopAdminRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/sales': {
      id: '/_authenticated/tools/sales'
      path: '/sales'
      fullPath: '/tools/sales'
      preLoaderRoute: typeof AuthenticatedToolsSalesRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/player': {
      id: '/_authenticated/tools/player'
      path: '/player'
      fullPath: '/tools/player'
      preLoaderRoute: typeof AuthenticatedToolsPlayerRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/market': {
      id: '/_authenticated/tools/market'
      path: '/market'
      fullPath: '/tools/market'
      preLoaderRoute: typeof AuthenticatedToolsMarketRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/leaderboard': {
      id: '/_authenticated/tools/leaderboard'
      path: '/leaderboard'
      fullPath: '/tools/leaderboard'
      preLoaderRoute: typeof AuthenticatedToolsLeaderboardRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/faction': {
      id: '/_authenticated/tools/faction'
      path: '/faction'
      fullPath: '/tools/faction'
      preLoaderRoute: typeof AuthenticatedToolsFactionRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/events': {
      id: '/_authenticated/tools/events'
      path: '/events'
      fullPath: '/tools/events'
      preLoaderRoute: typeof AuthenticatedToolsEventsRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/clicker': {
      id: '/_authenticated/tools/clicker'
      path: '/clicker'
      fullPath: '/tools/clicker'
      preLoaderRoute: typeof AuthenticatedToolsClickerRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/tools/alerts': {
      id: '/_authenticated/tools/alerts'
      path: '/alerts'
      fullPath: '/tools/alerts'
      preLoaderRoute: typeof AuthenticatedToolsAlertsRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/staff/appeals': {
      id: '/_authenticated/staff/appeals'
      path: '/appeals'
      fullPath: '/staff/appeals'
      preLoaderRoute: typeof AuthenticatedStaffAppealsRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/announce': {
      id: '/_authenticated/staff/announce'
      path: '/announce'
      fullPath: '/staff/announce'
      preLoaderRoute: typeof AuthenticatedStaffAnnounceRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/members/$id': {
      id: '/_authenticated/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AuthenticatedMembersIdRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/verify-audit-chain': {
      id: '/api/public/hooks/verify-audit-chain'
      path: '/api/public/hooks/verify-audit-chain'
      fullPath: '/api/public/hooks/verify-audit-chain'
      preLoaderRoute: typeof ApiPublicHooksVerifyAuditChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-discord-presence': {
      id: '/api/public/hooks/sync-discord-presence'
      path: '/api/public/hooks/sync-discord-presence'
      fullPath: '/api/public/hooks/sync-discord-presence'
      preLoaderRoute: typeof ApiPublicHooksSyncDiscordPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scan-anomalies': {
      id: '/api/public/hooks/scan-anomalies'
      path: '/api/public/hooks/scan-anomalies'
      fullPath: '/api/public/hooks/scan-anomalies'
      preLoaderRoute: typeof ApiPublicHooksScanAnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-automation': {
      id: '/api/public/hooks/run-automation'
      path: '/api/public/hooks/run-automation'
      fullPath: '/api/public/hooks/run-automation'
      preLoaderRoute: typeof ApiPublicHooksRunAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-application-reviews': {
      id: '/api/public/hooks/process-application-reviews'
      path: '/api/public/hooks/process-application-reviews'
      fullPath: '/api/public/hooks/process-application-reviews'
      preLoaderRoute: typeof ApiPublicHooksProcessApplicationReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paladium-sync': {
      id: '/api/public/hooks/paladium-sync'
      path: '/api/public/hooks/paladium-sync'
      fullPath: '/api/public/hooks/paladium-sync'
      preLoaderRoute: typeof ApiPublicHooksPaladiumSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paladium-status-sync': {
      id: '/api/public/hooks/paladium-status-sync'
      path: '/api/public/hooks/paladium-status-sync'
      fullPath: '/api/public/hooks/paladium-status-sync'
      preLoaderRoute: typeof ApiPublicHooksPaladiumStatusSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paladium-market-sync': {
      id: '/api/public/hooks/paladium-market-sync'
      path: '/api/public/hooks/paladium-market-sync'
      fullPath: '/api/public/hooks/paladium-market-sync'
      preLoaderRoute: typeof ApiPublicHooksPaladiumMarketSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paladium-faction-sync': {
      id: '/api/public/hooks/paladium-faction-sync'
      path: '/api/public/hooks/paladium-faction-sync'
      fullPath: '/api/public/hooks/paladium-faction-sync'
      preLoaderRoute: typeof ApiPublicHooksPaladiumFactionSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/paladium-admin-shop-sync': {
      id: '/api/public/hooks/paladium-admin-shop-sync'
      path: '/api/public/hooks/paladium-admin-shop-sync'
      fullPath: '/api/public/hooks/paladium-admin-shop-sync'
      preLoaderRoute: typeof ApiPublicHooksPaladiumAdminShopSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-mc-stats': {
      id: '/api/public/hooks/import-mc-stats'
      path: '/api/public/hooks/import-mc-stats'
      fullPath: '/api/public/hooks/import-mc-stats'
      preLoaderRoute: typeof ApiPublicHooksImportMcStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-salary-preview': {
      id: '/api/public/hooks/generate-salary-preview'
      path: '/api/public/hooks/generate-salary-preview'
      fullPath: '/api/public/hooks/generate-salary-preview'
      preLoaderRoute: typeof ApiPublicHooksGenerateSalaryPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-digest': {
      id: '/api/public/hooks/generate-digest'
      path: '/api/public/hooks/generate-digest'
      fullPath: '/api/public/hooks/generate-digest'
      preLoaderRoute: typeof ApiPublicHooksGenerateDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/voice': {
      id: '/api/public/bot/voice'
      path: '/api/public/bot/voice'
      fullPath: '/api/public/bot/voice'
      preLoaderRoute: typeof ApiPublicBotVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/stats': {
      id: '/api/public/bot/stats'
      path: '/api/public/bot/stats'
      fullPath: '/api/public/bot/stats'
      preLoaderRoute: typeof ApiPublicBotStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/message': {
      id: '/api/public/bot/message'
      path: '/api/public/bot/message'
      fullPath: '/api/public/bot/message'
      preLoaderRoute: typeof ApiPublicBotMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/member': {
      id: '/api/public/bot/member'
      path: '/api/public/bot/member'
      fullPath: '/api/public/bot/member'
      preLoaderRoute: typeof ApiPublicBotMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/mc-link-confirm': {
      id: '/api/public/bot/mc-link-confirm'
      path: '/api/public/bot/mc-link-confirm'
      fullPath: '/api/public/bot/mc-link-confirm'
      preLoaderRoute: typeof ApiPublicBotMcLinkConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/import': {
      id: '/api/public/bot/import'
      path: '/api/public/bot/import'
      fullPath: '/api/public/bot/import'
      preLoaderRoute: typeof ApiPublicBotImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/members/$id/warnings': {
      id: '/api/staff/members/$id/warnings'
      path: '/api/staff/members/$id/warnings'
      fullPath: '/api/staff/members/$id/warnings'
      preLoaderRoute: typeof ApiStaffMembersIdWarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/members/$id/notes': {
      id: '/api/staff/members/$id/notes'
      path: '/api/staff/members/$id/notes'
      fullPath: '/api/staff/members/$id/notes'
      preLoaderRoute: typeof ApiStaffMembersIdNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/query/profil': {
      id: '/api/public/bot/query/profil'
      path: '/api/public/bot/query/profil'
      fullPath: '/api/public/bot/query/profil'
      preLoaderRoute: typeof ApiPublicBotQueryProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/query/points': {
      id: '/api/public/bot/query/points'
      path: '/api/public/bot/query/points'
      fullPath: '/api/public/bot/query/points'
      preLoaderRoute: typeof ApiPublicBotQueryPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/query/don-valider': {
      id: '/api/public/bot/query/don-valider'
      path: '/api/public/bot/query/don-valider'
      fullPath: '/api/public/bot/query/don-valider'
      preLoaderRoute: typeof ApiPublicBotQueryDonValiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/query/candidatures': {
      id: '/api/public/bot/query/candidatures'
      path: '/api/public/bot/query/candidatures'
      fullPath: '/api/public/bot/query/candidatures'
      preLoaderRoute: typeof ApiPublicBotQueryCandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersIdRoute: typeof AuthenticatedMembersIdRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersIdRoute: AuthenticatedMembersIdRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffAnnounceRoute: typeof AuthenticatedStaffAnnounceRoute
  AuthenticatedStaffAppealsRoute: typeof AuthenticatedStaffAppealsRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffAnnounceRoute: AuthenticatedStaffAnnounceRoute,
  AuthenticatedStaffAppealsRoute: AuthenticatedStaffAppealsRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedToolsRouteChildren {
  AuthenticatedToolsAlertsRoute: typeof AuthenticatedToolsAlertsRoute
  AuthenticatedToolsClickerRoute: typeof AuthenticatedToolsClickerRoute
  AuthenticatedToolsEventsRoute: typeof AuthenticatedToolsEventsRoute
  AuthenticatedToolsFactionRoute: typeof AuthenticatedToolsFactionRoute
  AuthenticatedToolsLeaderboardRoute: typeof AuthenticatedToolsLeaderboardRoute
  AuthenticatedToolsMarketRoute: typeof AuthenticatedToolsMarketRoute
  AuthenticatedToolsPlayerRoute: typeof AuthenticatedToolsPlayerRoute
  AuthenticatedToolsSalesRoute: typeof AuthenticatedToolsSalesRoute
  AuthenticatedToolsShopAdminRoute: typeof AuthenticatedToolsShopAdminRoute
  AuthenticatedToolsStatusRoute: typeof AuthenticatedToolsStatusRoute
  AuthenticatedToolsUptimeRoute: typeof AuthenticatedToolsUptimeRoute
  AuthenticatedToolsXpCalculatorRoute: typeof AuthenticatedToolsXpCalculatorRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
}

const AuthenticatedToolsRouteChildren: AuthenticatedToolsRouteChildren = {
  AuthenticatedToolsAlertsRoute: AuthenticatedToolsAlertsRoute,
  AuthenticatedToolsClickerRoute: AuthenticatedToolsClickerRoute,
  AuthenticatedToolsEventsRoute: AuthenticatedToolsEventsRoute,
  AuthenticatedToolsFactionRoute: AuthenticatedToolsFactionRoute,
  AuthenticatedToolsLeaderboardRoute: AuthenticatedToolsLeaderboardRoute,
  AuthenticatedToolsMarketRoute: AuthenticatedToolsMarketRoute,
  AuthenticatedToolsPlayerRoute: AuthenticatedToolsPlayerRoute,
  AuthenticatedToolsSalesRoute: AuthenticatedToolsSalesRoute,
  AuthenticatedToolsShopAdminRoute: AuthenticatedToolsShopAdminRoute,
  AuthenticatedToolsStatusRoute: AuthenticatedToolsStatusRoute,
  AuthenticatedToolsUptimeRoute: AuthenticatedToolsUptimeRoute,
  AuthenticatedToolsXpCalculatorRoute: AuthenticatedToolsXpCalculatorRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
}

const AuthenticatedToolsRouteWithChildren =
  AuthenticatedToolsRoute._addFileChildren(AuthenticatedToolsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAbsencesRoute: typeof AuthenticatedAbsencesRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedBacklogRoute: typeof AuthenticatedBacklogRoute
  AuthenticatedBlacklistRoute: typeof AuthenticatedBlacklistRoute
  AuthenticatedClassementRoute: typeof AuthenticatedClassementRoute
  AuthenticatedClassementPointsRoute: typeof AuthenticatedClassementPointsRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedPointsRoute: typeof AuthenticatedPointsRoute
  AuthenticatedRecruitmentRoute: typeof AuthenticatedRecruitmentRoute
  AuthenticatedShopRoute: typeof AuthenticatedShopRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRouteWithChildren
  AuthenticatedTrialsRoute: typeof AuthenticatedTrialsRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAbsencesRoute: AuthenticatedAbsencesRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedBacklogRoute: AuthenticatedBacklogRoute,
  AuthenticatedBlacklistRoute: AuthenticatedBlacklistRoute,
  AuthenticatedClassementRoute: AuthenticatedClassementRoute,
  AuthenticatedClassementPointsRoute: AuthenticatedClassementPointsRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedPointsRoute: AuthenticatedPointsRoute,
  AuthenticatedRecruitmentRoute: AuthenticatedRecruitmentRoute,
  AuthenticatedShopRoute: AuthenticatedShopRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedToolsRoute: AuthenticatedToolsRouteWithChildren,
  AuthenticatedTrialsRoute: AuthenticatedTrialsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CandidatureRoute: CandidatureRoute,
  ForbiddenRoute: ForbiddenRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthTestLoginRoute: ApiAuthTestLoginRoute,
  ApiAuthWhoamiRoute: ApiAuthWhoamiRoute,
  ApiPublicMarketRoute: ApiPublicMarketRoute,
  ApiTestLoginRoute: ApiTestLoginRoute,
  ApiTestSeedPollRoute: ApiTestSeedPollRoute,
  ApiPublicBotImportRoute: ApiPublicBotImportRoute,
  ApiPublicBotMcLinkConfirmRoute: ApiPublicBotMcLinkConfirmRoute,
  ApiPublicBotMemberRoute: ApiPublicBotMemberRoute,
  ApiPublicBotMessageRoute: ApiPublicBotMessageRoute,
  ApiPublicBotStatsRoute: ApiPublicBotStatsRoute,
  ApiPublicBotVoiceRoute: ApiPublicBotVoiceRoute,
  ApiPublicHooksGenerateDigestRoute: ApiPublicHooksGenerateDigestRoute,
  ApiPublicHooksGenerateSalaryPreviewRoute:
    ApiPublicHooksGenerateSalaryPreviewRoute,
  ApiPublicHooksImportMcStatsRoute: ApiPublicHooksImportMcStatsRoute,
  ApiPublicHooksPaladiumAdminShopSyncRoute:
    ApiPublicHooksPaladiumAdminShopSyncRoute,
  ApiPublicHooksPaladiumFactionSyncRoute:
    ApiPublicHooksPaladiumFactionSyncRoute,
  ApiPublicHooksPaladiumMarketSyncRoute: ApiPublicHooksPaladiumMarketSyncRoute,
  ApiPublicHooksPaladiumStatusSyncRoute: ApiPublicHooksPaladiumStatusSyncRoute,
  ApiPublicHooksPaladiumSyncRoute: ApiPublicHooksPaladiumSyncRoute,
  ApiPublicHooksProcessApplicationReviewsRoute:
    ApiPublicHooksProcessApplicationReviewsRoute,
  ApiPublicHooksRunAutomationRoute: ApiPublicHooksRunAutomationRoute,
  ApiPublicHooksScanAnomaliesRoute: ApiPublicHooksScanAnomaliesRoute,
  ApiPublicHooksSyncDiscordPresenceRoute:
    ApiPublicHooksSyncDiscordPresenceRoute,
  ApiPublicHooksVerifyAuditChainRoute: ApiPublicHooksVerifyAuditChainRoute,
  ApiPublicBotQueryCandidaturesRoute: ApiPublicBotQueryCandidaturesRoute,
  ApiPublicBotQueryDonValiderRoute: ApiPublicBotQueryDonValiderRoute,
  ApiPublicBotQueryPointsRoute: ApiPublicBotQueryPointsRoute,
  ApiPublicBotQueryProfilRoute: ApiPublicBotQueryProfilRoute,
  ApiStaffMembersIdNotesRoute: ApiStaffMembersIdNotesRoute,
  ApiStaffMembersIdWarningsRoute: ApiStaffMembersIdWarningsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
