// This file is automatically generated. Do not edit it directly.
// AVERTISSEMENT : `attachSupabaseAuth` ne fait QUE joindre un éventuel bearer
// Supabase aux RPC TanStack côté client. Ce n'est PAS un contrôle d'accès.
// L'authentification réelle de l'app passe par les cookies Discord chiffrés
// (src/lib/auth/session.server.ts) et l'autorisation par requirePermission
// (src/lib/auth/require.server.ts).
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
